In [1]:
import numpy as np 
from flask import Flask , redirect , render_template
import scipy as sc 
import sympy as sp 
import matplotlib.pyplot as plt
from   datetime import date,datetime,timezone,timedelta

import  sqlite3 as sq 


A = np.array([[1,2,30],[40,50,-98],[80,98,77]])
B  = np.array([[8,-98,54],[87,98,970],[14,85,98]])

print(A)
print(B)


[[  1   2  30]
 [ 40  50 -98]
 [ 80  98  77]]
[[  8 -98  54]
 [ 87  98 970]
 [ 14  85  98]]
